name: main branch CI
run-name: ${{ github.actor }} pushed to main branch 🚀
on:
  push:
    branches:
      - main
jobs:
  Test-Frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: cd frontend
      - run: pwd
      - run: npm ci
      - run: npm run test
# Test-Backend
#  Build-App:
#    xxx
#  Build-Image: