name: main branch CI
run-name: ${{ github.actor }} pushed to main branch 🚀
on:
  push:
    branches:
      - main
jobs:
  Test-Frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: node --version
      - run: npm --version
      - run: cd frontend
      - run: npm ci
      - run: npm run test
# Test-Backend
#  Build-App:
#    xxx
#  Build-Image: