name: main branch CI
run-name: ${{ github.actor }} pushed to main branch 🚀
on:
  push:
    branches:
      - main
jobs:
  Test-Frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: |
          cd frontend
          pwd
          npm ci
          npm run test

  Test-Backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run test
        shell: bash
        run: |
          cd backend
          ./gradlew test

  Build-Image:
    runs-on: ubuntu-latest
    needs:
      - Test-Backend
      - Test-Frontend
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build Container Image
        run: |
          cd frontend 
          npm i
          npm run build
          mv ./dist ../backend/src/main/resources/static
          
          cd ../backend
          ls ./src/main/resources/static
          ./gradlew bootBuildImage
          docker images
# Test-Backend
#  Build-App:
#    xxx
#  Build-Image: